-- GMRef_Data.lua
-- Donnees completes : commandes, reputations, professions

GMRef_Data = {}

-- ============================================================
--  COMMANDES -- 8 categories
-- ============================================================
GMRef_Data.Commands = {

    {
        group = "Personnage & Niveau",
        entries = {
            { cmd = ".levelup [n]",                         desc = "Augmente le niveau de la cible de n niveaux" },
            { cmd = ".character level [nom] [n]",           desc = "Definit le niveau exact (en ligne ou hors ligne)" },
            { cmd = ".reset level [nom]",                   desc = "Reinitialise le niveau a 1 (stats et talents inclus)" },
            { cmd = ".reset talents [nom]",                 desc = "Reinitialise les talents (spec actuelle + pets)" },
            { cmd = ".reset specs [nom]",                   desc = "Supprime tous les talents des deux specs" },
            { cmd = ".reset spells [nom]",                  desc = "Supprime tous les sorts non-originaux" },
            { cmd = ".reset stats [nom]",                   desc = "Recalcule toutes les stats au niveau actuel" },
            { cmd = ".reset honor [nom]",                   desc = "Reinitialise toutes les donnees d'honneur" },
            { cmd = ".maxskill",                            desc = "Monte toutes les competences au maximum" },
            { cmd = ".save",                                desc = "Sauvegarde le personnage actuel" },
            { cmd = ".saveall",                             desc = "Sauvegarde tous les personnages en ligne" },
            { cmd = ".character rename [nom]",              desc = "Marque pour renommage a la prochaine connexion" },
            { cmd = ".character customize [nom]",           desc = "Marque pour personnalisation a la prochaine connexion" },
            { cmd = ".repairitems",                         desc = "Repare tous les objets du personnage cible" },
            { cmd = ".pinfo [nom]",                         desc = "Affiche les infos de compte du joueur cible" },
            { cmd = ".guid",                                desc = "Affiche le GUID de la cible selectionnee" },
            { cmd = ".distance [nom]",                      desc = "Affiche la distance entre vous et la cible" },
            { cmd = ".gps [nom]",                           desc = "Affiche coordonnees X/Y/Z, orientation, map ID, zone ID" },
        },
    },

    {
        group = "Objets & Sorts",
        entries = {
            { cmd = ".additem [ID]",                        desc = "Ajoute un objet a la cible (lien chat OK)" },
            { cmd = ".additem [ID] [n]",                    desc = "Ajoute n exemplaires de l'objet" },
            { cmd = ".additemset [ID]",                     desc = "Ajoute un set complet d'equipement" },
            { cmd = ".lookup item [nom]",                   desc = "Recherche un objet par nom (anglais)" },
            { cmd = ".lookup itemset [nom]",                desc = "Recherche un set d'objets par nom" },
            { cmd = ".lookup spell [nom]",                  desc = "Recherche un sort par nom" },
            { cmd = ".lookup skill [nom]",                  desc = "Recherche une competence par nom" },
            { cmd = ".lookup quest [nom]",                  desc = "Recherche une quete par nom" },
            { cmd = ".lookup creature [nom]",               desc = "Recherche une creature par nom" },
            { cmd = ".lookup object [nom]",                 desc = "Recherche un gameobject par nom" },
            { cmd = ".lookup faction [nom]",                desc = "Recherche une faction par nom et retourne son ID" },
            { cmd = ".lookup area [nom]",                   desc = "Recherche une zone par nom" },
            { cmd = ".lookup tele [nom]",                   desc = "Recherche un lieu de teleportation" },
            { cmd = ".lookup taxinode [nom]",               desc = "Recherche un noeud de taxi par nom" },
            { cmd = ".lookup title [nom]",                  desc = "Recherche un titre par nom" },
            { cmd = ".learn [ID]",                          desc = "Apprend le sort associe a cet ID" },
            { cmd = ".learn [ID] all",                      desc = "Apprend tous les rangs du sort" },
            { cmd = ".learn all",                           desc = "Apprend un large ensemble de sorts utiles (admin)" },
            { cmd = ".learn all_crafts",                    desc = "Apprend toutes les professions et recettes" },
            { cmd = ".learn all_default [nom]",             desc = "Apprend tous les sorts de depart race/classe + quetes" },
            { cmd = ".learn all_gm",                        desc = "Apprend tous les sorts par defaut pour les GMs" },
            { cmd = ".learn all_lang",                      desc = "Apprend toutes les langues" },
            { cmd = ".learn all_myclass",                   desc = "Apprend tous les sorts et talents de sa classe" },
            { cmd = ".learn all_myspells",                  desc = "Apprend tous les sorts (hors talents) de sa classe" },
            { cmd = ".learn all_mytalents",                 desc = "Apprend tous les talents de sa classe" },
            { cmd = ".learn all_recipes [profession]",      desc = "Toutes les recettes d'une profession + skill au max" },
            { cmd = ".unlearn [ID]",                        desc = "Desapprend le sort (ajouter 'all' pour tous les rangs)" },
            { cmd = ".list talents",                        desc = "Affiche tous les talents connus du personnage" },
        },
    },

    {
        group = "Quetes & Guildes",
        entries = {
            { cmd = ".quest add [ID]",                      desc = "Ajoute la quete au journal du personnage" },
            { cmd = ".quest complete [ID]",                 desc = "Marque tous les objectifs comme completes" },
            { cmd = ".quest remove [ID]",                   desc = "Retire la quete du journal" },
            { cmd = ".guild create [leader] [nom]",         desc = "Cree une guilde avec le joueur cible/nomme comme leader" },
            { cmd = ".guild delete [nom]",                  desc = "Supprime la guilde (nom entre guillemets)" },
            { cmd = ".guild invite [joueur] [guilde]",      desc = "Invite un joueur dans une guilde" },
            { cmd = ".guild uninvite [joueur]",             desc = "Retire un joueur de sa guilde" },
            { cmd = ".guild rank [joueur] [rang]",          desc = "Definit le rang du joueur dans la guilde" },
            { cmd = ".titles add [ID]",                     desc = "Ajoute un titre a la liste des titres connus" },
            { cmd = ".titles current [ID]",                 desc = "Definit le titre actif du joueur" },
            { cmd = ".titles remove [ID]",                  desc = "Retire un titre de la liste" },
            { cmd = ".honor add [montant]",                 desc = "Ajoute un montant d'honneur (gains du jour)" },
            { cmd = ".honor addkill",                       desc = "Ajoute l'unite ciblee comme kill PvP du jour" },
            { cmd = ".flusharenapoints",                    desc = "Distribue les points d'arene et commence une nouvelle semaine" },
            { cmd = ".instance listbinds",                  desc = "Liste tous les locks d'instance du joueur cible" },
            { cmd = ".instance unbind all",                 desc = "Supprime tous les locks d'instance" },
            { cmd = ".instance unbind [mapid]",             desc = "Supprime le lock de la map specifiee" },
        },
    },

    {
        group = "Teleportation",
        entries = {
            { cmd = ".tele [nom]",                          desc = "Teleporte vers un lieu nomme (anglais)" },
            { cmd = ".tele name [joueur] [lieu]",           desc = "Teleporte un autre joueur vers un lieu" },
            { cmd = ".tele group [lieu]",                   desc = "Teleporte le groupe entier vers un lieu" },
            { cmd = ".tele add [nom]",                      desc = "Enregistre votre position comme destination .tele" },
            { cmd = ".tele del [nom]",                      desc = "Supprime une destination de la liste .tele" },
            { cmd = ".lookup tele [nom]",                   desc = "Recherche une destination de teleportation" },
            { cmd = ".recall [nom]",                        desc = "Retour a la position avant le dernier tp" },
            { cmd = ".game [nom]",                          desc = "Teleporte vers un joueur" },
            { cmd = ".goname [nom]",                        desc = "Teleporte vers un joueur (peut etre hors ligne)" },
            { cmd = ".namego [nom]",                        desc = "Teleporte un joueur vers vous (peut etre hors ligne)" },
            { cmd = ".groupgo [nom]",                       desc = "Teleporte le joueur et son groupe vers vous" },
            { cmd = ".go xy [x] [y] [mapid]",              desc = "Teleporte vers coordonnees X/Y (sol/eau)" },
            { cmd = ".go xyz [x] [y] [z] [mapid]",         desc = "Teleporte vers coordonnees X/Y/Z exactes" },
            { cmd = ".go zonexy [x] [y] [zone]",           desc = "Teleporte vers coordonnees client dans une zone" },
            { cmd = ".go grid [gridX] [gridY] [mapid]",    desc = "Teleporte au centre d'une grille de map" },
            { cmd = ".go creature [GUID]",                  desc = "Teleporte vers une creature via son GUID" },
            { cmd = ".go object [GUID]",                    desc = "Teleporte vers un gameobject via son GUID" },
            { cmd = ".go graveyard [id]",                   desc = "Teleporte vers un cimetiere par son ID" },
            { cmd = ".go taxinode [id]",                    desc = "Teleporte vers un noeud de taxi par son ID" },
            { cmd = ".go trigger [id]",                     desc = "Teleporte vers un areatrigger par son ID" },
        },
    },

    {
        group = "Combat & Mode GM",
        entries = {
            { cmd = ".gm on",                               desc = "Active le mode GM (invisibilite aux monstres)" },
            { cmd = ".gm off",                              desc = "Desactive le mode GM" },
            { cmd = ".gm chat on",                          desc = "Affiche le symbole Blizzard devant votre nom en chat" },
            { cmd = ".gm chat off",                         desc = "Masque le symbole Blizzard" },
            { cmd = ".gm fly on",                           desc = "Active le vol pour la cible" },
            { cmd = ".gm fly off",                          desc = "Desactive le vol pour la cible" },
            { cmd = ".gm visible on",                       desc = "Rend le GM visible pour les autres joueurs" },
            { cmd = ".gm visible off",                      desc = "Rend le GM invisible pour les autres joueurs" },
            { cmd = ".gm ingame",                           desc = "Liste les GMs actuellement connectes" },
            { cmd = ".gm list",                             desc = "Affiche tous les comptes GM et leurs niveaux" },
            { cmd = ".gm setview",                          desc = "Active la vue a la premiere personne sur l'unite ciblee" },
            { cmd = ".whispers on",                         desc = "Active la reception de chuchotements de joueurs" },
            { cmd = ".whispers off",                        desc = "Desactive la reception de chuchotements" },
            { cmd = ".the",                                 desc = "Tue la cible instantanement" },
            { cmd = ".damage [n]",                          desc = "Inflige n degats a la cible" },
            { cmd = ".revive",                              desc = "Ressuscite le joueur cible" },
            { cmd = ".respawn",                             desc = "Fait reapparaitre la creature ciblee" },
            { cmd = ".combatstop [nom]",                    desc = "Arrete le combat du personnage cible" },
            { cmd = ".cooldown [spellid]",                  desc = "Supprime tous les cooldowns (ou celui du sort specifie)" },
            { cmd = ".aura [spellid]",                      desc = "Ajoute l'aura du sort a l'unite ciblee" },
            { cmd = ".unaura [spellid]",                    desc = "Retire l'aura du sort de l'unite ciblee" },
            { cmd = ".cast [spellid]",                      desc = "Lance le sort sur la cible" },
            { cmd = ".cast back [spellid]",                 desc = "La cible lance le sort sur vous" },
            { cmd = ".cast self [spellid]",                 desc = "La cible lance le sort sur elle-meme" },
            { cmd = ".cast target [spellid]",               desc = "La cible lance le sort sur sa propre victime" },
        },
    },

    {
        group = "Modificateurs",
        entries = {
            { cmd = ".modify speed [n]",                    desc = "Vitesse de course (multiplicateur 0.1-10)" },
            { cmd = ".modify swim [n]",                     desc = "Vitesse de nage" },
            { cmd = ".modify fly [n]",                      desc = "Vitesse de vol" },
            { cmd = ".modify bwalk [n]",                    desc = "Vitesse de marche arriere" },
            { cmd = ".modify aspeed [n]",                   desc = "Toutes les vitesses simultanement" },
            { cmd = ".modify hp [n]",                       desc = "Points de vie" },
            { cmd = ".modify mana [n]",                     desc = "Mana" },
            { cmd = ".modify energy [n]",                   desc = "Energie" },
            { cmd = ".modify rage [n]",                     desc = "Rage" },
            { cmd = ".modify money [n]",                    desc = "Argent (en cuivre, negatif pour retirer)" },
            { cmd = ".modify morph [displayid]",            desc = "Apparence via un ID de modele" },
            { cmd = ".demorph",                             desc = "Annule le morph et restaure l'apparence d'origine" },
            { cmd = ".modify scale [n]",                    desc = "Taille de la cible" },
            { cmd = ".modify gender male/female",           desc = "Genre du personnage cible" },
            { cmd = ".modify drunk [0-100]",                desc = "Niveau d'ivresse (0=sobre, 100=ivre mort)" },
            { cmd = ".modify mount [id] [speed]",           desc = "Affiche le personnage en monture via un ID de creature" },
            { cmd = ".modify tp [n]",                       desc = "Points de talent libres" },
            { cmd = ".modify rep [ID] [valeur]",            desc = "Reputation avec une faction (0=Neutre, ~43000=Exalte)" },
            { cmd = ".modify phase [phasemask]",            desc = "Phasemask du personnage cible" },
            { cmd = ".taxicheat on",                        desc = "Debloque temporairement tous les noeuds de taxi" },
            { cmd = ".taxicheat off",                       desc = "Retire l'acces a tous les noeuds de taxi" },
            { cmd = ".explorecheat 1",                      desc = "Revele toute la carte du monde" },
            { cmd = ".explorecheat 0",                      desc = "Masque toute la carte du monde" },
            { cmd = ".waterwalk on",                        desc = "Permet de marcher sur l'eau" },
            { cmd = ".waterwalk off",                       desc = "Desactive la marche sur l'eau" },
            { cmd = ".showarea [areaid]",                   desc = "Revele la zone specifiee sur la carte" },
            { cmd = ".hidearea [areaid]",                   desc = "Masque la zone specifiee sur la carte" },
            { cmd = ".wchange [1/2/3] [0/1]",              desc = "Meteo : 1=pluie, 2=neige, 3=sable -- 0=off, 1=on" },
        },
    },

    {
        group = "NPC & Monde",
        entries = {
            { cmd = ".npc add [entry_id]",                  desc = "Spawn une creature a votre position" },
            { cmd = ".npc delete",                          desc = "Supprime la creature ciblee" },
            { cmd = ".npc move",                            desc = "Deplace le point de spawn a votre position" },
            { cmd = ".npc changelevel [n]",                 desc = "Change le niveau de la creature ciblee (1-63)" },
            { cmd = ".npc factionid [id]",                  desc = "Change la faction de la creature ciblee" },
            { cmd = ".npc flag [flag]",                     desc = "Definit les NPC flags de la creature" },
            { cmd = ".npc setmodel [displayid]",            desc = "Change le modele visuel de la creature ciblee" },
            { cmd = ".npc setmovetype stay/random/way",     desc = "Type de mouvement : statique / aleatoire / waypoints" },
            { cmd = ".npc spawndist [dist]",                desc = "Ajuste la distance de spawn de la creature" },
            { cmd = ".npc spawntime [time]",                desc = "Ajuste le temps de respawn de la creature" },
            { cmd = ".npc follow",                          desc = "La creature ciblee commence a vous suivre" },
            { cmd = ".npc unfollow",                        desc = "La creature ciblee arrete de vous suivre" },
            { cmd = ".npc say [texte]",                     desc = "Fait parler la creature ciblee en chat" },
            { cmd = ".npc yell [texte]",                    desc = "Fait crier la creature ciblee" },
            { cmd = ".npc playemote [emoteid]",             desc = "Fait jouer une emote a la creature ciblee" },
            { cmd = ".npc tame",                            desc = "Apprivoise la creature ciblee" },
            { cmd = ".npc additem [itemid]",                desc = "Ajoute un objet a la liste du marchand cible" },
            { cmd = ".npc delitem [itemid]",                desc = "Retire un objet de la liste du marchand cible" },
            { cmd = ".npc info",                            desc = "Affiche toutes les infos detaillees du NPC cible" },
            { cmd = ".wp add",                              desc = "Ajoute votre position comme waypoint pour la creature" },
            { cmd = ".wp show on/off/info",                 desc = "Affiche les waypoints visuellement en jeu" },
            { cmd = ".wp modify [parametre]",               desc = "Modifie un waypoint (waittime, emote, spell, del...)" },
            { cmd = ".gobject add [id]",                    desc = "Place un gameobject a votre position" },
            { cmd = ".gobject delete [guid]",               desc = "Supprime le gameobject par son GUID" },
            { cmd = ".gobject move [guid]",                 desc = "Deplace le gameobject a votre position" },
            { cmd = ".gobject turn [guid] [angle]",         desc = "Fait pivoter le gameobject autour de l'axe Z" },
            { cmd = ".gobject near [distance]",             desc = "Liste les gameobjects a portee (defaut 10 unites)" },
            { cmd = ".gobject target [id|nom]",             desc = "Localise le gameobject le plus proche" },
            { cmd = ".list creature [id]",                  desc = "Liste les creatures avec cet entry ID dans le monde" },
            { cmd = ".list item [id]",                      desc = "Liste tous les emplacements de l'objet" },
            { cmd = ".list object [id]",                    desc = "Liste les gameobjects avec cet entry ID" },
            { cmd = ".trigger near [distance]",             desc = "Liste les areatriggers a portee" },
            { cmd = ".event list",                          desc = "Affiche les evenements du monde actifs" },
            { cmd = ".event start [id]",                    desc = "Demarre un evenement du monde" },
            { cmd = ".event stop [id]",                     desc = "Arrete un evenement du monde" },
            { cmd = ".debug play sound [id]",               desc = "Joue un son pour vous seul" },
            { cmd = ".debug play cinematic [id]",           desc = "Lance une cinematique en jeu" },
            { cmd = ".debug play movie [id]",               desc = "Joue une video cinematique" },
            { cmd = ".debug anim [emoteid]",                desc = "Joue une animation d'emote sur votre personnage" },
        },
    },

    {
        group = "Compte & Serveur",
        entries = {
            { cmd = ".account",                             desc = "Affiche le niveau d'acces de votre compte" },
            { cmd = ".account create [nom] [mdp]",          desc = "Cree un nouveau compte" },
            { cmd = ".account delete [nom]",                desc = "Supprime un compte et tous ses personnages" },
            { cmd = ".account password [ancien] [nv] [nv]", desc = "Change le mot de passe de votre compte" },
            { cmd = ".account lock on/off",                 desc = "Restreint la connexion a l'IP actuelle" },
            { cmd = ".account onlinelist",                  desc = "Affiche la liste des comptes connectes" },
            { cmd = ".account set gmlevel [nom] [niv]",     desc = "Definit le niveau GM d'un compte (0-3)" },
            { cmd = ".account set addon [nom] [0/1/2]",     desc = "Extension autorisee : 0=Vanilla, 1=TBC, 2=WotLK" },
            { cmd = ".ban account [nom] [duree] [raison]",  desc = "Banni un compte et kick le joueur" },
            { cmd = ".ban character [nom] [duree] [raison]",desc = "Banni le compte du personnage et le kick" },
            { cmd = ".ban ip [ip] [duree] [raison]",        desc = "Banni une adresse IP" },
            { cmd = ".unban account [nom]",                 desc = "Leve le ban sur un compte" },
            { cmd = ".unban character [nom]",               desc = "Leve le ban sur un personnage" },
            { cmd = ".unban ip [ip]",                       desc = "Leve le ban sur une IP" },
            { cmd = ".baninfo account [id]",                desc = "Infos completes sur un ban de compte" },
            { cmd = ".banlist account [nom]",               desc = "Liste les bans de comptes" },
            { cmd = ".kick [nom]",                          desc = "Kick le joueur du serveur" },
            { cmd = ".mute [nom] [minutes]",                desc = "Coupe le chat du joueur pour X minutes" },
            { cmd = ".unmute [nom]",                        desc = "Retablit le chat du joueur" },
            { cmd = ".announce [texte]",                    desc = "Message global a tous les joueurs (chat log)" },
            { cmd = ".notify [texte]",                      desc = "Message global affiche a l'ecran de tous" },
            { cmd = ".send mail [joueur] [sujet] [texte]",  desc = "Envoie un mail a un joueur" },
            { cmd = ".send money [joueur] [sujet] [texte] [montant]", desc = "Envoie de l'argent par mail" },
            { cmd = ".server info",                         desc = "Version du serveur et nombre de joueurs" },
            { cmd = ".server motd",                         desc = "Affiche le message du jour" },
            { cmd = ".server set motd [texte]",             desc = "Definit le message du jour" },
            { cmd = ".server shutdown [delai]",             desc = "Arrete le serveur apres X secondes" },
            { cmd = ".server shutdown cancel",              desc = "Annule le timer d'arret" },
            { cmd = ".server restart [delai]",              desc = "Redemarre le serveur apres X secondes" },
            { cmd = ".server restart cancel",               desc = "Annule le timer de redemarrage" },
            { cmd = ".server exit",                         desc = "Termine mangosd immediatement" },
            { cmd = ".reload all",                          desc = "Recharge toutes les tables supportees" },
            { cmd = ".reload config",                       desc = "Recharge le fichier mangosd.conf" },
            { cmd = ".reload all_loot",                     desc = "Recharge toutes les tables de loot" },
            { cmd = ".reload all_scripts",                  desc = "Recharge toutes les tables *_scripts" },
            { cmd = ".ticket on/off",                       desc = "Active/desactive l'affichage des tickets GM" },
            { cmd = ".ticket [n]",                          desc = "Affiche le ticket numero n" },
            { cmd = ".delticket all",                       desc = "Supprime tous les tickets du serveur" },
            { cmd = ".character deleted list [nom]",        desc = "Liste les personnages supprimes" },
            { cmd = ".character deleted restore [guid]",    desc = "Restaure un personnage supprime" },
            { cmd = ".character deleted delete [guid]",     desc = "Supprime definitivement un personnage" },
        },
    },
}

-- ============================================================
--  REPUTATIONS
-- ============================================================
GMRef_Data.Reputations = {
    { group = "Alliance", color = { 0.5, 0.75, 1 }, entries = {
        { name = "Darnassus",               id = 69 },
        { name = "L'Exodar",                id = 930 },
        { name = "Forgefer",                id = 47 },
        { name = "Gnomes de Gnomeregan",    id = 54 },
        { name = "Hurlevent",               id = 72 },
    }},
    { group = "Horde", color = { 1, 0.5, 0.5 }, entries = {
        { name = "Blaireau-Tonnerre",       id = 81 },
        { name = "Trolls Sombrelance",      id = 530 },
        { name = "Orgrimmar",               id = 76 },
        { name = "Lune-d'Argent",           id = 911 },
        { name = "Undercity",               id = 68 },
    }},
    { group = "Classic -- General", color = { 0.85, 0.75, 0.4 }, entries = {
        { name = "Aube de l'Argent",            id = 529 },
        { name = "Boucaniers Sceau de Sang",    id = 87 },
        { name = "Couvee de Nozdormu",          id = 910 },
        { name = "Foire de Sombrelune",         id = 909 },
        { name = "Clan Gelkis",                 id = 92 },
        { name = "Bois-du-Val",                 id = 576 },
        { name = "Hydraxien",                   id = 749 },
        { name = "Clan Magram",                 id = 93 },
        { name = "Ravenholdt",                  id = 349 },
        { name = "Shen'dralar",                 id = 809 },
    }},
    { group = "Burning Crusade", color = { 0.85, 0.75, 0.4 }, entries = {
        { name = "Le Consortium",               id = 933 },
        { name = "L'Oeil Violet",               id = 967 },
        { name = "Les Mag'har",                 id = 941 },
        { name = "Gardiens du Sable",           id = 990 },
        { name = "La Ville-Honneur",            id = 946 },
        { name = "Expedition Cenarion",         id = 942 },
        { name = "Gardiens du Temps",           id = 989 },
        { name = "Kurenai",                     id = 978 },
        { name = "Nether-Defenseurs",           id = 1015 },
        { name = "Ogri'la",                     id = 1038 },
        { name = "Sporeggar",                   id = 970 },
        { name = "Thrallmar",                   id = 947 },
        { name = "Offensive Soleil Brise",      id = 1077 },
        { name = "Les Aldor",                   id = 932 },
        { name = "Les Voyants",                 id = 934 },
        { name = "Le Sha'tar",                  id = 935 },
        { name = "Bas-Quartier",                id = 1011 },
    }},
    { group = "Forces Alliance", color = { 0.5, 0.75, 1 }, entries = {
        { name = "Ligue d'Arathor",         id = 509 },
        { name = "Ailes d'Argent",          id = 890 },
        { name = "Garde Frostlance",        id = 730 },
    }},
    { group = "Forces Horde", color = { 1, 0.5, 0.5 }, entries = {
        { name = "Clan Loup-de-Givre",      id = 729 },
        { name = "Clan Vaisseaux de Guerre",id = 889 },
    }},
    { group = "Steamwheedle / Divers", color = { 0.7, 0.7, 0.7 }, entries = {
        { name = "Baie-du-Butin",           id = 21 },
        { name = "Gadgetzan",               id = 369 },
        { name = "Ratchet",                 id = 470 },
        { name = "Attente Eternelle",       id = 577 },
        { name = "Syndicat",                id = 70 },
        { name = "Clan Wildhammer",         id = 471 },
        { name = "Musardin d'Hiver",        id = 589 },
    }},
}

-- ============================================================
--  MACROS
-- ============================================================
GMRef_Data.Macros = {
    { label = "Alliance Classic", commands = {
        ".mod rep 69 999999",  ".mod rep 930 999999", ".mod rep 1134 999999",
        ".mod rep 54 999999",  ".mod rep 47 999999",  ".mod rep 890 999999",
        ".mod rep 730 999999", ".mod rep 72 999999",  ".mod rep 509 999999",
        ".mod rep 589 999999",
    }},
    { label = "Horde Classic", commands = {
        ".mod rep 1133 999999", ".mod rep 530 999999", ".mod rep 729 999999",
        ".mod rep 76 999999",   ".mod rep 911 999999", ".mod rep 510 999999",
        ".mod rep 81 999999",   ".mod rep 922 999999", ".mod rep 68 999999",
        ".mod rep 889 999999",
    }},
    { label = "Classic General 1", commands = {
        ".mod rep 529 99999", ".mod rep 87 99999",  ".mod rep 21 99999",
        ".mod rep 910 99999", ".mod rep 609 99999", ".mod rep 909 99999",
        ".mod rep 369 99999", ".mod rep 577 99999", ".mod rep 92 99999",
        ".mod rep 749 99999", ".mod rep 93 99999",  ".mod rep 470 99999",
        ".mod rep 349 99999",
    }},
    { label = "Classic General 2", commands = {
        ".mod rep 809 99999", ".mod rep 59 99999",  ".mod rep 576 99999",
        ".mod rep 270 99999", ".mod rep 70 99999",
    }},
    { label = "BC Alliance", commands = {
        ".mod rep 946 99999", ".mod rep 978 99999",
        ".mod rep 942 99999", ".mod rep 1012 99999",
    }},
    { label = "BC Horde", commands = {
        ".mod rep 941 99999", ".mod rep 947 99999",
        ".mod rep 942 99999", ".mod rep 1012 99999",
    }},
    { label = "BC General", commands = {
        ".mod rep 967 99999",  ".mod rep 935 99999", ".mod rep 934 99999",
        ".mod rep 990 99999",  ".mod rep 933 99999", ".mod rep 932 99999",
        ".mod rep 970 99999",  ".mod rep 1077 99999",".mod rep 1031 99999",
        ".mod rep 1038 99999", ".mod rep 1011 99999",".mod rep 1015 99999",
        ".mod rep 989 99999",
    }},
}

-- ============================================================
--  PROFESSIONS
-- ============================================================
GMRef_Data.Professions = {
    { name = "Forge",            learnId = 2018,  skillId = 164 },
    { name = "Enchantement",     learnId = 7411,  skillId = 333 },
    { name = "Ingenierie",       learnId = 4036,  skillId = 202 },
    { name = "Herboristerie",    learnId = 2366,  skillId = 182 },
    { name = "Joaillerie",       learnId = 25229, skillId = 755 },
    { name = "Travail du cuir",  learnId = 2108,  skillId = 165 },
    { name = "Minage",           learnId = 2575,  skillId = 186 },
    { name = "Pelleterie",       learnId = 8613,  skillId = 393 },
    { name = "Couture",          learnId = 3908,  skillId = 197 },
    { name = "Calligraphie",     learnId = 45357, skillId = 773 },
    { name = "Alchimie",         learnId = 2259,  skillId = 171 },
    { name = "Cuisine",          learnId = 2550,  skillId = 185 },
    { name = "Peche",            learnId = 7620,  skillId = 356 },
    { name = "Premiers secours", learnId = 3279,  skillId = 129 },
}
